package aoc.ksp

import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSValueParameter

/**
 * The generated companion source, one function per generation mode.
 *
 * Plain string templates rather than a codegen library: the output is small, and being able to read
 * the template and the generated file side by side is worth more here than type-safe construction.
 */
internal class CompanionTemplates(
    private val mappings: ParameterMappings,
) {
    private val supportedTypesDoc = SUPPORTED_TYPES.joinToString(", ")

    fun standard(
        packageName: String,
        className: String,
        parameters: List<KSValueParameter>,
        skips: String,
    ): String =
        """
            |package $packageName
            |
            |import aoc.ksp.BaseEntity
            |import aoc.ksp.IStructure${extraImports(packageName, parameters)}
            |
            |/**
            | * Generated by KSP StructureProcessor
            | * Standalone companion object that implements IStructure<$className>
            | *
            | * Supported field types:
            | * - $supportedTypesDoc
            | * - Any enum, matched by name ignoring case, with spaces read as underscores
            | * - Nullable variants of all types above
            | * - Custom types with @FieldConverter annotation
            | *
            | * Usage: ${className}Companion.fromLine(line, regex)
            | * Example:
            | *   val regex = Regex("(?<field1>\\d+) (?<field2>\\w+)")
            | *   val entity = ${className}Companion.fromLine("123 abc", regex)
            | *
            | * Note: Regex named groups must match field names exactly
            | */
            |object ${className}Companion : IStructure<$className> {$skips
            |    override fun create(collection: MatchGroupCollection): $className =
            |        $className(
            |${mappings.standard(parameters)},
            |        )
            |}
            |
        """.trimMargin()

    fun customLine(
        packageName: String,
        className: String,
        parameters: List<KSValueParameter>,
        skips: String,
    ): String =
        """
            |package $packageName
            |
            |import aoc.ksp.IStructureCustomLine
            |
            |/**
            | * Generated by KSP StructureProcessor
            | * Standalone companion object that implements IStructureCustomLine<$className>
            | *
            | * This companion processes the entire line and match sequence,
            | * allowing for custom parsing logic that goes beyond simple field extraction.
            | *
            | * Usage: ${className}Companion.fromLine(line, regex)
            | * Example:
            | *   val regex = Regex("[A-Z][a-z]?")
            | *   val entity = ${className}Companion.fromLine("CaRnAlBSi", regex)
            | *
            | * Note: The create method receives both the line and all matches
            | */
            |object ${className}Companion : IStructureCustomLine<$className> {$skips
            |    override fun create(
            |        line: String,
            |        collection: Sequence<MatchResult>,
            |    ): $className =
            |        $className(
            |${mappings.customLine(parameters)},
            |        )
            |}
            |
        """.trimMargin()

    fun multiStructure(
        packageName: String,
        className: String,
        sealedSubclasses: List<KSClassDeclaration>,
        discriminatorField: String,
        skips: String,
    ): String {
        val subclassParameters = sealedSubclasses.flatMap { it.primaryConstructor?.parameters.orEmpty() }

        // Resolved once, so the documented mapping and the generated `when` cases cannot drift.
        val tokenBySubclass = mappings.discriminatorTokens(sealedSubclasses)

        return """
            |package $packageName
            |
            |import aoc.ksp.BaseEntity
            |import aoc.ksp.IStructureMulti${extraImports(packageName, subclassParameters)}
            |
            |/**
            | * Generated by KSP StructureProcessor
            | * Standalone companion object that implements IStructureMulti<$className>
            | *
            | * Routes to the appropriate sealed subclass based on discriminator field '$discriminatorField'.
            | *
            | * Discriminator mapping (uppercased group value -> subclass); the token is the
            | * subclass name, so a rename changes what the subclass answers to:
            |${tokenBySubclass.entries.joinToString("\n") { (subclass, token) ->
            " * - \"$token\" -> ${subclass.simpleName.asString()}"
        }}
            | *
            | * Usage: ${className}Companion.fromLine(line, regexArray)
            | * Example:
            | *   val regexArray = arrayOf(
            | *       Regex("(?<cmd>jmp) (?<offset>[+-]\\d+)"),
            | *       Regex("(?<cmd>inc) (?<register>[a-z]+)")
            | *   )
            | *   val instruction = ${className}Companion.fromLine("jmp +10", regexArray)
            | *
            | * Note: Regex named groups must match field names exactly
            | * Note: Discriminator field '$discriminatorField' is used to determine the subclass
            | */
            |object ${className}Companion : IStructureMulti<$className> {$skips
            |    override fun create(collection: MatchGroupCollection): $className {
            |        val discriminator = BaseEntity.getAsString(collection, "$discriminatorField").uppercase()
            |        return when (discriminator) {
            |${mappings.sealedSubclassCases(tokenBySubclass, className)}
            |
            |            else -> {
            |                throw IllegalArgumentException("Unknown discriminator value: ${"$"}discriminator in $className creation")
            |            }
            |        }
            |    }
            |}
            |
            """.trimMargin()
    }

    /**
     * `override val` lines for the non-zero skip counts, formatted so they can be spliced into a
     * companion body. Zero is the [IStructureSkips] default, so an entity that asks for no trimming
     * generates exactly what it generated before the skips existed.
     */
    fun skipOverrides(
        skipHeaderLines: Int,
        skipFooterLines: Int,
    ): String {
        val overrides =
            buildList {
                if (skipHeaderLines > 0) add("skipHeaderLines" to skipHeaderLines)
                if (skipFooterLines > 0) add("skipFooterLines" to skipFooterLines)
            }

        if (overrides.isEmpty()) return ""
        return overrides.joinToString(
            separator = "",
            prefix = "\n",
        ) { (name, count) -> "|    override val $name: Int = $count\n" } + "|"
    }

    /**
     * Import lines for everything [parameters] name that the generated file does not already import:
     * the `@FieldConverter` objects it calls, and the enum classes it names as type arguments.
     *
     * Formatted so they can be appended directly after the last fixed import in a template. Enums
     * declared alongside the entity are skipped - they resolve without an import, and emitting one
     * would make every existing companion of a same-package entity churn.
     */
    private fun extraImports(
        packageName: String,
        parameters: List<KSValueParameter>,
    ): String {
        val converters =
            parameters.mapNotNull { param ->
                mappings
                    .converterTypeOf(param)
                    ?.declaration
                    ?.qualifiedName
                    ?.asString()
            }

        val enums =
            parameters
                .mapNotNull { param -> mappings.enumDeclarationOf(param) }
                .filter { it.packageName.asString() != packageName }
                .mapNotNull { it.qualifiedName?.asString() }

        val imports = (converters + enums).toCollection(LinkedHashSet())

        if (imports.isEmpty()) return ""
        return "\n|${imports.joinToString("\n") { "import $it" }}"
    }
}
